Fix dependencies
StanfordHCI/indie-label pull request #7
Opened 2024-06-15 00:42 UTC by EvanPartidas

2024-06-15 00:48 UTC, matheusmaldaner commented
Thank you for pointing out the conflicting package versions Evan, I believe I ended up using "npm install --legacy-peer-deps" when first installing the packages to ignore the conflicts, but your way is definitely better.

2024-06-15 00:48 UTC, matheusmaldaner approved these changes

2024-06-20 04:39 UTC, michelle123lam requested changes
Thanks for making these changes!

2024-06-20 04:40 UTC, michelle123lam approved these changes

2024-06-20 04:40 UTC, merged